version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: dpe_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dpe_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017/pricing
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dpe_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongo_data:
